// Cloudflare/OpenNext custom worker entrypoint.
//
// The generated OpenNext worker only exports `fetch`. Production continuity in
// Cloudflare needs a real Workers `scheduled()` handler; Vercel-style
// `vercel.json` crons are ignored by Workers deployments. This wrapper reuses
// the generated fetch handler and invokes the existing cron route handlers on
// each Cloudflare Cron Trigger.

// @ts-ignore `.open-next/worker.js` is generated by @opennextjs/cloudflare at build/deploy time.
import { default as handler } from "./.open-next/worker.js"

type WorkerExecutionContext = {
  waitUntil?: (promise: Promise<unknown>) => void
  passThroughOnException?: () => void
}

type WorkerScheduledController = {
  cron?: string
  scheduledTime?: number
}

const INTERNAL_ORIGIN = "https://cts-v-yd.internal"
const CRON_PATHS = [
  "/api/cron/server-continuity",
  "/api/cron/sync-live-positions",
] as const

async function invokeCronPath(path: (typeof CRON_PATHS)[number], env: unknown, ctx: WorkerExecutionContext): Promise<void> {
  const request = new Request(`${INTERNAL_ORIGIN}${path}`, {
    method: "GET",
    headers: {
      "User-Agent": "cloudflare-scheduled-worker",
      "x-cloudflare-cron": "1",
    },
  })

  const response = await handler.fetch(request, env, ctx)
  if (!response.ok) {
    const text = await response.text().catch(() => "")
    throw new Error(`${path} failed with ${response.status}${text ? `: ${text.slice(0, 500)}` : ""}`)
  }
}

export default {
  fetch: handler.fetch,

  async scheduled(_controller: WorkerScheduledController, env: unknown, ctx: WorkerExecutionContext) {
    const tasks = CRON_PATHS.map((path) => invokeCronPath(path, env, ctx))
    const results = await Promise.allSettled(tasks)
    const failures = results.filter((result): result is PromiseRejectedResult => result.status === "rejected")
    if (failures.length > 0) {
      throw new Error(
        failures
          .map((failure) => (failure.reason instanceof Error ? failure.reason.message : String(failure.reason)))
          .join("; "),
      )
    }
  },
}

// Re-export generated OpenNext Durable Objects if present. OpenNext documents
// this as required when an app uses its DO queue/tag-cache features.
// @ts-ignore `.open-next/worker.js` is generated by @opennextjs/cloudflare.
export { DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js"
